### ISSUE TITLE
8048S043C problems

### ISSUE THREAD

**Issue by rzeldent** [rzeldent/esp32-smartdisplay#102]
Hi Stojos,

Speed is indeed a bit slow on the 8048S043C. Increasing the pixel buffer does not help much. Increasing the PCLK creates glitching... 
And indeed GT911 does not function. Schematics are hard to find but think the I2C values are correct. Added to the todo list...

**Comment by biremk** [comment]
I have the same problem. The factory demo code works very fast. However, smartdisplay is slow.

**Comment by rzeldent** [comment]
Slowness is solved using SPI ram and define for Pixel buffer. Is now blazing fast!
