### ISSUE TITLE
Changes on 2432S028R_BGR board (2023-03-28), display looks garbled

### ISSUE THREAD

**Issue by maxbrito500** [rzeldent/esp32-smartdisplay#12]
Hello,

I've ordered a new model 2432S028R because the touch screen stopped working. When receiving the new unit (2023-03-28) based on the same model, the display is looking garbled. The solution to make the display is to decrease the SPI clock value.

It was changed from 80000000 to 50000000.

Changes made:
`#define ILI9341_SPI_FREQ 50000000`

I've then tested the same code on the older board, the new SPI_FREQ is still valid.

Just sharing the information with others.

**Comment by mermetbt** [comment]
Thanks! It solved the issue on my side.

Unfortunately we cannot define the value from "outside" which force the change to be made directly in the code of the library.

**Comment by rzeldent** [comment]
Updated this setting in the library.
