### ISSUE TITLE
configurable display draw buffer support

### ISSUE THREAD

**Issue by PingguSoft** [rzeldent/esp32-smartdisplay#122]
display update is so slow for boards with big resolution.
it is caused by LVGL_PIXEL_BUFFER_LINES is limited to 16.
I think it is better to give options such as SPIRAM and lines for drawBuffer.

With esp32-4848S040CIY1 board, below changes show fast display update.

```
void smartdisplay_init()
{
<snip>
//   uint drawBufferPixels = LCD_WIDTH * LVGL_PIXEL_BUFFER_LINES;
//   void *drawBuffer = heap_caps_malloc(sizeof(lv_color16_t) * drawBufferPixels, MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);

  uint drawBufferPixels = LCD_WIDTH * LCD_HEIGHT;
  void *drawBuffer = heap_caps_malloc(sizeof(lv_color16_t) * drawBufferPixels, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
```

thanks.

**Comment by rzeldent** [comment]
Excellent suggestion. Focus was on stability and get the displays working but this indeed should make it much more usable!

**Comment by rzeldent** [comment]
Is now in [develop](https://github.com/rzeldent/esp32-smartdisplay/tree/develop)

Also did this for other boards, let's hope it works as well as the esp32-8048S070 (that was really slow)
Thanks again,
