### ISSUE TITLE
ESP32-2424S012N/C blank display

### ISSUE THREAD

**Issue by TheCooolNerd** [rzeldent/esp32-smartdisplay#129]
Hi, 

I have the 1.2 inch round display. 
The demo code uploads fine with no errors. I can see the backlight light up but nothing on the screen. 
The serial monitor just shows this :

`14:49:40.777 -> ESP-ROM:esp32c3-api1-20210207
14:49:40.777 -> Build:Feb  7 2021
14:49:40.777 -> rst:0x15 (USB_UART_CHIP_RESET),boot:0xc (SPI_FAST_FLASH_BOOT)
14:49:40.777 -> Saved PC:0x4206bcca
14:49:40.777 -> SPIWP:0xee
14:49:40.777 -> mode:DIO, clock div:1
14:49:40.777 -> load:0x3fcd5810,len:0x438
14:49:40.777 -> load:0x403cc710,len:0x90c
14:49:40.777 -> load:0x403ce710,len:0x25f4
14:49:40.777 -> entry 0x403cc710`

The code is running as i can see the board connect to the wifi network in the listed devices. 

Dont know how to begin troubleshooting.

**Comment by rzeldent** [comment]
Hi Coool nerd,

What version are you using?

**Comment by TheCooolNerd** [comment]
Library : Latest
Demo : latest
All downloaded within the span of last week.

**Comment by rzeldent** [comment]
There has been a release yesterday so doubt you have the latest version if you downloaded this last week.

**Comment by TheCooolNerd** [comment]
How can i check/update the library/demo version?

**Comment by rzeldent** [comment]
guess the simplest is to clone it in a new direcory

**Comment by TheCooolNerd** [comment]
cloned the demo to a new directory with the submodules
selected my board in the platformio.ini by removing the # 
uploaded the project.
same issue. backlight turns on, black display. 
same output on the serial monitor

**Comment by rzeldent** [comment]
Retested and confirmed. For now use an older version. Wil take a look at it. You can also compare it to previous versions.

**Comment by TheCooolNerd** [comment]
Thank you. will compare and see if any changes make sense to me. 
for now the only thing that pops is that even though the flash mode is qio, the serial output says DIO. may be irrelevant as well.

**Comment by rzeldent** [comment]
Found typo introduced during refactoring. You can switch to the develop branch or apply https://github.com/rzeldent/esp32-smartdisplay/commit/bb656fd383c51bde94e531549db0f0f0b2646bc4

NB boards are also updated to have logging output at boot

Enjoy!

![PXL_20240211_172534472](https://github.com/rzeldent/esp32-smartdisplay/assets/7620231/464b308a-0a33-4235-9d20-092b41c7ca2f)

**Comment by rzeldent** [comment]
Thanks for reporting the issue!
