### ISSUE TITLE
ESP32-2432S022C - Touch initialization problems

### ISSUE THREAD

**Issue by Nostromo0** [rzeldent/esp32-smartdisplay#132]
Hello there,
I'm having an issue with running the demo project with a ESP32-2432S022C board:

```
E (463) lcd_panel.io.i2c: panel_io_i2c_rx_buffer(128): i2c transaction failed
E (469) CST816S: read_id(176): I2C read failed
E (474) CST816S: esp_lcd_touch_new_i2c_cst816s(86): Read version failed
E (480) CST816S: Initialization failed!
```
This happens on `lvgl_touch_init`

Any idea what might be the problem?
Thanks.

**Comment by Nostromo0** [comment]
I also tried to use the board's factory sample project using the Arduino IDE but it gave me a I2C timeout error

**Comment by rzeldent** [comment]
Do you have a photo of the board? To what controller is present (or none)...

**Comment by Nostromo0** [comment]
I'll send you pictures as soon as i can.
Right now i can only give you the link i bought the board from:
https://aliexpress.com/item/1005006102451859.html

**Comment by Nostromo0** [comment]
Here they are:
![20240215_171158.jpg](https://github.com/rzeldent/esp32-smartdisplay/assets/83037309/73dcef51-e66d-4438-93b3-63d6978f2d81)

![20240215_171207.jpg](https://github.com/rzeldent/esp32-smartdisplay/assets/83037309/e26512b4-9f65-4479-8348-aceafc7c4318)

**Comment by rzeldent** [comment]
Thanks!

IO think the U6: 
<img width="338" alt="image" src="https://github.com/rzeldent/esp32-smartdisplay/assets/7620231/a8ae3a57-4912-43c2-bee4-3e2633a659f3">

Is an xpt2046 so resistive...

**Comment by rzeldent** [comment]
Assume this was the issue?

**Comment by Nostromo0** [comment]
Hello there, it appears that i have been using the wrong model the whole time when compiling the project.
I'm sorry if i may have caused you to waste any time. I'm also gonna go ahead and close the issue.
Thanks for developing this amazing library!
