### ISSUE TITLE
ESP32-3248S035C Display not rotating

### ISSUE THREAD

**Issue by ae9000** [rzeldent/esp32-smartdisplay#144]
Hello,
I am trying to get the library working on the ESP32-3248S035C board that uses the ST7796 display driver and has a resolution of 320x480. In portrait mode, everything works as expected:

![20240315_175610](https://github.com/rzeldent/esp32-smartdisplay/assets/115202201/469ea0d9-cff0-4ea9-9edb-2b8a17c35d1f)

 but when rotated using the `lv_disp_set_rotation(disp, LV_DISP_ROT_90);` command it seems like internally the rotation happens, but the pixels don't get drawn to the display in the right order:

![20240315_175535](https://github.com/rzeldent/esp32-smartdisplay/assets/115202201/cd722f41-d6e6-41a5-adc4-0b103302b932)

Here's what the main code looks like:
```
#include <Arduino.h>
#include <esp32_smartdisplay.h>
#include <ui/ui.h>

void setup() {
  // put your setup code here, to run once:
  
   smartdisplay_init(); //setup display and touch
   auto disp = lv_disp_get_default();
   lv_disp_set_rotation(disp, LV_DISP_ROT_90);
   smartdisplay_led_set_rgb(500&0x01, 300&0x02, 0&0x04);
    ui_init();//don't forget
}

void loop() {
  // put your main code here, to run repeatedly:
  lv_timer_handler();
} 

```
I don't know if I'm doing something wrong, or if there is a bug with the specific setup I'm using.
Thank you for the help.

**Comment by rzeldent** [comment]
Hi ae9000,

Could reproduce this! Still unclear why. Will look at this...

**Comment by rzeldent** [comment]
Something is not right with the hardware rotation. Have to dig deeper.
For now, you can use software rotation:

in the file esp32_smartdisplay\src\lvgl_panel_st7796_spi.c, change the software rotation to:
```drv->sw_rotate = 1;```
  
So the lvgl_lcd_init function looks like:

```
void lvgl_lcd_init(lv_disp_drv_t *drv)
{
    log_v("drv:0x%08x");

    // Hardware rotation is for now disabled
    drv->sw_rotate = 1;
    drv->rotated = LV_DISP_ROT_NONE;
```

**Comment by ae9000** [comment]
That works. Thank you so much.

**Comment by rzeldent** [comment]
Should work now in the 2.0.9 relase
