### ISSUE TITLE
 esp32-8048S070C

### ISSUE THREAD

**Issue by GastonHP** [rzeldent/esp32-smartdisplay#147]
Hello great code! 
 I used it for two esp32-displays : esp32-2432S028R and  esp32-8048S070C.  For the first one, it works beautiful.  But for the second one, code compiled but gave no display.  Looking at the serial output I found two issues in the lvgl_panel_st7262_par.c file and modified the code this way:
![image](https://github.com/rzeldent/esp32-smartdisplay/assets/23199843/054090de-805f-4770-8bb7-8798227d4dc5)
then it compiled and worked!

**Comment by rzeldent** [comment]
Confirmed, build in driver does not support mirroring/swapping

**Comment by GastonHP** [comment]
Thanks for your fix, but it seems you forgot to comment the line concerning the swapxy?

Regards,

G. Herpoel
________________________________
De : Rene ***@***.***>
Envoyé : mercredi 20 mars 2024 08:10
À : rzeldent/esp32-smartdisplay ***@***.***>
Cc : Ghislain Herpoel ***@***.***>; Author ***@***.***>
Objet : Re: [rzeldent/esp32-smartdisplay] esp32-8048S070C (Issue #147)


Confirmed, build in driver does not support mirroring/swapping

**Comment by rzeldent** [comment]
Yes, you're right. Thanks, Fixed!
