### ISSUE TITLE
smartdisplay_lcd_adaptive_brightness_cds not exposed

### ISSUE THREAD

**Issue by olivluca** [rzeldent/esp32-smartdisplay#155]
The readme says that you can use the `smartdisplay_lcd_adaptive_brightness_cds` callback to enable adaptive brightness.
The function is present in esp32_smartdisplay.c but it's not exposed by any header.
If I add the definition to esp32_smartdisplay.h I can use it in my project and it actually works.

**Comment by rzeldent** [comment]
Added definition in header in the develop.
Will be present with the next release...

Thanks for mentioning. I was still tweaking it a bit but is indeed maybe already enough...

**Comment by olivluca** [comment]
Thank you
