### ISSUE TITLE
ESP32-8048S043C  sdcard configuration for plattformio

### ISSUE THREAD

**Issue by joekam54** [rzeldent/esp32-smartdisplay#158]
Hi, first thank you for the great work you have done! here.

I would like to play mjp and jpeg file from the sdcard.  How shouldI set up the sdcard config for platformio? 
Your helpp is very appriciated.

**Comment by rzeldent** [comment]
Hi Joe,

There is a duplicate issue about this and so far have not found a solution as this hardware related...

**Comment by joekam54** [comment]
Hi Rene,
Thank you! This s a very good input, for now I do not need touch so maybe somehow getting SDcard working will help, because I would like to play out pictures and Video on this Display from the SD card.

**Comment by plueschpruem** [comment]
I second this!
Not being able to use the SD is kinda sad since this is otherwise a very nice library!

**Comment by rzeldent** [comment]
Take a look at (or continue at)https://github.com/rzeldent/esp32-smartdisplay/issues/143
