### ISSUE TITLE
esp32-2432s028

### ISSUE THREAD

**Issue by YosefGoodman** [rzeldent/esp32-smartdisplay#16]
i got this board and i am wondering how i should put this software onto the board, and which library i should use once i upload it.

and i saw you mention a few codes, like smartdisplay_init(); and smartdisplay_set_led_color(lv_color32_t rgb); where can i find the library with all the codes that where created with this specific software?

**Comment by rzeldent** [comment]
Hi Yosef,

Take a look at the demo application: https://github.com/rzeldent/esp32-smartdisplay-demo
