### ISSUE TITLE
esp32-8048S070C Slowing becoming unresponsive

### ISSUE THREAD

**Issue by lesintheusa** [rzeldent/esp32-smartdisplay#166]
Firstly What a great Project I love it :) How do I contribute some cash to say Thank you.

The problem I am experiencing is when I run only the LGVL Portion nothing else.
At startup, it works fine. However gradually over time the CPU usage drops gradually and after about 12 hours the CPU% is around 1% and the display becomes unresponsive.
Is there a setting I am missing or is it a bug?
I am using Squareline to Create my screens and placing the Squareline code in the UI folder.

Best Regards Les

**Comment by rzeldent** [comment]
Hi Les,

You're using the demo application?

This sounds like a memory leak. However, there is also the LVGL memory usage on the left.
I suggest to add logging to display the available memory so this can be ruled out....

This logging is already present in the startup() function.
So write down the free memory at the start and display this again in the loop() function.
