### ISSUE TITLE
8048S043C touch incorrect descriptor in boards/esp32-8048S043C.json

### ISSUE THREAD

**Issue by ralphrmartin** [rzeldent/esp32-smartdisplay#190]
The boards/esp32-8048S043C.json as supplied with the demo project leads to applications in which touch input does not work.

If I change
GT911_TOUCH_CONFIG_INT_GPIO_NUM=18
to
GT911_TOUCH_CONFIG_INT_GPIO_NUM=GPIO_NUM_NC
everything works as expected. 

I'd suggest this change needs making in the master copy of
boards/esp32-8048S043C.json

**Comment by rzeldent** [comment]
See https://github.com/rzeldent/esp32-smartdisplay/issues/189

**Comment by ralphrmartin** [comment]
See my reply to #189.

**Comment by rzeldent** [comment]
Close issue and keep #189.
