### ISSUE TITLE
Why Change Screen Event To Main Screen Freezes the UI

### ISSUE THREAD

**Issue by Tejas2017610** [rzeldent/esp32-smartdisplay#194]
Board: CYD ESP32-4827S043C
SquareLine Studio Version: 1.4.2
Graphics Library: Arduino with TFT_eSPI and LVGL 9.1.0
Issue: UI Freeze and Image Button Rendering Problem

When using an image button, pressing the button causes a rendering issue where the image does not display correctly. Despite this, the screen still transitions to the next screen. However, when trying to return to the first screen by pressing any button on the subsequent screen, the entire UI freezes, and nothing on the screen responds.
Cause Identified

The issue appears to be related to the use of the transform scale property on the image button. When transform scale is applied to make the image button appear smaller, it causes the UI to freeze when returning to the first screen.

**Comment by rzeldent** [comment]
Hi Tejas,

Your description gives very little info to look into this issue. Are you using the esp32-smartdisplay library or the SquaureLine libraries?
A hint is to enable logging in LVGL in the ```lv_conf.h``` file, option LV_USE_LOG.

Good luck!

**Comment by Tejas2017610** [comment]
No used Square Line Studio Library with Custom ui. 
yes checked with logging but its just stuck so not responds
and think its problem occurs with Image button Transform Scale property as i remove its usage and its working fine.
Thanx : )
