### ISSUE TITLE
WiFi STA

### ISSUE THREAD

**Issue by dbuggz** [rzeldent/esp32-smartdisplay#20]
HI,
I have an ESDP-2432S028R and am running the lvgl_pushbutton example. The ESP never connects to my WiFi, and I cannot find an AP. Is there a 'secrets' file I should be using?

Regards
Dave

**Comment by alfem** [comment]
Where can I copy that file from?

**Comment by rzeldent** [comment]
Hi Alfonso,

I looked again and this demo (think you're referring to https://github.com/rzeldent/esp32-smartdisplay-demo/) has no WiFi. It is just a demo application. I got a bit confused because thought it was for another application: https://github.com/rzeldent/esp32-flightradar24-ttgo...

**Comment by alfem** [comment]
Thanks for your answer. I am not completely mad, then :-)
