### ISSUE TITLE
Use it only with tft_espi not lvgl?

### ISSUE THREAD

**Issue by jaksatomovic** [rzeldent/esp32-smartdisplay#22]
I noticed if i create simple peripheral ble code with boilerplate od your demo app flash is alreday on 99 percent. So i am wondering will removing lvlg lib and usi g only tft_espi help a bit and is it possible at all?

**Comment by rzeldent** [comment]
Hi jaksatomovic,

Sure you can, the whole point of this library is to have lvgl.

Regards,

Rene
