### ISSUE TITLE
Updates to readme.md

### ISSUE THREAD

**Issue by smileymiley** [rzeldent/esp32-smartdisplay#223]
Hi, I looked at this project for the first time, seems to be just what I need, but while setting up following the instructions I found a couple of issues with the documentation:

1. Step 5 where is says "This file must be copied to the include directory and renamed to lvgl_conf.h"  but it should be renamed to lv_conf.h

2. Step 6 where it says "-D LV_CONF_PATH="${PROJECT_DIR}/example/lv_conf.h" it would be better to replace path /example/ with /include/ to be consistent with the instructions in step 5

3. Step 7 would be better to have these at the top to avoid missing smart display references
#include <Arduino.h>
#include <esp32_smartdisplay.h>

4. Step 7 in the loop() it is missing 
  auto const now = millis();

Also I was getting 

error: 'lv_display_t' {aka 'struct lv_display_t'} has no member named 'sw_rotate' 

when using 

lib_deps = 
   	rzeldent/esp32_smartdisplay

but changing to 

lib_deps =
	https://github.com/rzeldent/esp32-smartdisplay.git

resolved it, I don't know why, maybe the source for the first one needs updating.

Hope it helps!
Thanks

**Comment by rzeldent** [comment]
Hi Smileymiley,

Am updating the readme with your feedback. Thank you!

Rene
