### ISSUE TITLE
Additional Flash

### ISSUE THREAD

**Issue by MkMunich** [rzeldent/esp32-smartdisplay#23]
Hi, I bought a ESP32-3248S035C, where U4 is not equipped. Does someone know, which flash I could solder? I've seen in the Sunton specs a 25Q32 4MB flush. My question is, whether also a Winbond 25Q64FV 8MB flush would work?
Best Regards

**Comment by rzeldent** [comment]
The R and C layouts are almost the same (except the touch interface).

Take a look at the annotated board: https://github.com/rzeldent/esp32-smartdisplay/blob/main/assets/schematics/ESP32-3248S035R-PCB.pdf. Here you see the flash memory and pinout.
