### ISSUE TITLE
ESP32-2432S024 (C/R) Variants

### ISSUE THREAD

**Issue by busbuyukefe** [rzeldent/esp32-smartdisplay#27]
Hi, there is a new variant I found on AliExpress with a 2.4" ili9341 based lcd with capacitive and resistive touchscreen options, a powerbank IC (IP5306) for using it with lithium batteries and an USB Type C port for programming.

https://www.aliexpress.com/item/1005005865107357.html

The only problem is the capacitive version has the CST820 driver chip, I couldn't find the datasheet for the chip but I was able to find an arduino sketch that can read touch points from the touchscreen. 

https://gist.github.com/busbuyukefe/4a17159627c3ea83b4994f346002f061

I can confirm this code works for the touchscreen.

I tried to create a wrapper based on your library but I couldn't manage to get it done, do you think it is possible to add CST820 functionality without much work?

**Comment by rzeldent** [comment]
Hi Busybuyukefe,

The link is to the original board? Or is it the board but with another capacitive controller chip?
This should be possible... Code does not look very complicated...

**Comment by busbuyukefe** [comment]
Yes it is the link to the board ESP32-2432S024, they sell it in 3 variants (capacitive, resisitve, and no touchscreen) I bought a few of the capacitive touch versions and they have CST820 touch controller ic on them.
![cst1](https://github.com/rzeldent/esp32-smartdisplay/assets/13920840/0bfde711-1d49-486e-84da-fffb1cc5ae6a)
![cst2](https://github.com/rzeldent/esp32-smartdisplay/assets/13920840/e1001148-0f46-45f4-b6ca-c6eb8ff67eb5)

**Comment by rzeldent** [comment]
Looks like a new revision of the 2432S035 board, let's hope only the controller has changed...

**Comment by busbuyukefe** [comment]
> Looks like a new revision of the 2432S035 board, let's hope only the controller has changed...

Yes I can confirm only the touch controller (and maybe the backlight pwm pin) is changed. I was able to get display output with your demo.

**Comment by rzeldent** [comment]
Hi,

Made a new branch with those boards. Untested as I do not own them.
Maybe you can give it a try?

**Comment by rzeldent** [comment]
Nice!!!

I updated the branch with your findings; the spi_ili9431 was a typo/copy paste...
Gesture None was indeed something that I thought about...

Give it a try to see if this works, then I can merge it!

**Comment by busbuyukefe** [comment]
There were a few changes that needed to be done, I created a PR  #12  for the needed changes, now It works without a problem thanks to your work :)

**Comment by rzeldent** [comment]
Hi Busbuyuke,

Thanks for the PR and these fixes... Merged the branch so should be available!
