### ISSUE TITLE
Blue and red inverted

### ISSUE THREAD

**Issue by edo44** [rzeldent/esp32-smartdisplay#3]
I have the two colors inverted for some reason when using LVGL. Any help?

**Comment by rzeldent** [comment]
Hi Edo,

You can try to change the MADCTL value. This is currently defined like this (depending on the orientation)
static const uint8_t madctl[] = {MADCTL_MY | MADCTL_RGB}; // Portrait 0 Degrees

so change the color channels to BGR:
static const uint8_t madctl[] = {MADCTL_MY | **MADCTL_BGR**}; // Portrait 0 Degrees

Let me know if this helps. What are you using as display board?

**Comment by edo44** [comment]
> 

yep, that solves the problem, thank you very much

ESP32_3248S035C

**Comment by rzeldent** [comment]
Strange, I have also a ESP32_3248S035C and this worked with the MADCTL_RGB settings.
Maybe there are different panels? Maybe need to be configurable in the defines...

**Comment by edo44** [comment]
> Strange, I have also a ESP32_3248S035C and this worked with the MADCTL_RGB settings. Maybe there are different panels? Maybe need to be configurable in the defines...

![photo_2023-02-10_16-33-11](https://user-images.githubusercontent.com/13797216/218131617-9c12fd32-0ae2-428f-a0bf-fd62613ad734.jpg)

**Comment by rzeldent** [comment]
![PXL_20230210_153958557.jpg](https://user-images.githubusercontent.com/7620231/218133221-5d866b81-a336-429a-9a14-d609c1237a7f.jpg)

**Comment by rzeldent** [comment]
This is mine; they look identical. I suspect the LCD panel might be another type....
Maybe some other users can share if they've also this problem?

**Comment by edo44** [comment]
![immagine](https://user-images.githubusercontent.com/13797216/218136496-50600ea6-3d71-47aa-8c28-b50404e21f28.png)

**Comment by rzeldent** [comment]
This is the capacitive touch controller

**Comment by edo44** [comment]
> This is the capacitive touch controller

I see, I thought it was the tft screen controller

**Comment by rzeldent** [comment]
Hi edo,

Made this setting an optional define and pushed a new version (1.0.4) to PlatformIO.

Enjoy!
