### ISSUE TITLE
Error while I install the library

### ISSUE THREAD

**Issue by ll1234567890** [rzeldent/esp32-smartdisplay#36]
I get this error:
Invalid library found in C:\Users\lavy1\Documents\Arduino\libraries\esp32-smartdisplay-1.0.8: Missing 'paragraph' from library

**Comment by rzeldent** [comment]
Are you using platformIO or arduino?

**Comment by ll1234567890** [comment]
arduino

**Comment by rzeldent** [comment]
It has been made for platformIO. 
You can try to zip it and try to install the zip file.
Otherwise copy the files from this repo...
