### ISSUE TITLE
Can't turn off performance and memory monitor

### ISSUE THREAD

**Issue by edo44** [rzeldent/esp32-smartdisplay#5]
In lv_conf.h LV_USE_USER_DATA 0 and LV_USE_MEM_MONITOR 0 don't disable the little monitor windows.

Is it maybe a driver thing?

ESP32_3248S035C

**Comment by rzeldent** [comment]
Hi edo,

his is something managed by LVGL. Have you checked the include path?
You should define your own config file...

Success

**Comment by edo44** [comment]
> Hi edo,
> 
> his is something managed by LVGL. Have you checked the include path? You should define your own config file...
> 
> Success

Yes, the include path is correct. Every other define works properly except for these two so I tought it was display driver thing.

I will ask in the LVGL section too. Thank you.
