### ISSUE TITLE
Empty screen at ESP32-2432S032C

### ISSUE THREAD

**Issue by Keidran** [rzeldent/esp32-smartdisplay#70]
LED blinking
The screen backlights work, but the screen is empty (demo)

[   297][I][main.cpp:26] setup(): CPU: ESP32-D0WD-V3 rev3, CPU Freq: 240 Mhz, 2 core(s)
[   298][I][main.cpp:27] setup(): Free heap: 248652 bytes
[   300][I][main.cpp:28] setup(): Free PSRAM: 0 bytes
[   305][I][main.cpp:29] setup(): SDK version: v4.4.6-dirty

![HA58-BFT6aY](https://github.com/rzeldent/esp32-smartdisplay/assets/64165043/35a2d780-d59e-4cf5-bbc0-7597393558d2)
![3lo-V2R_0Lg](https://github.com/rzeldent/esp32-smartdisplay/assets/64165043/42479dcf-56f8-4c65-8fbd-3256e547165e)

**Comment by rzeldent** [comment]
Hi Keidran,

See this an cyd with USB-C. Do not have this one in possession. and you're using SDK 4.4.6 (I'm using SDK version: v4.4.5).
What application and branch are you using?

**Comment by Keidran** [comment]
I build Demo from master.
Driver: ST7789 (from specifications)
Platform: Espressif 32 6.5.0
The screen backlights reacts to the change in light from the photoresistor.
Switching LV_COLOR_16_SWAP does not change anything.

**Comment by rzeldent** [comment]
Will have to take a look. Are you using PlatformIo?

**Comment by Keidran** [comment]
Yes

**Comment by Keidran** [comment]
Okey. 
In ESP32-2432S032C.json, the ST7796 driver was set, its change to ST7789 solved the problem.
Also, I changed SPI_MODE0 to SPI_MODE3

**Comment by rzeldent** [comment]
Yes, I checked the Sunton demo and the driver is indeed ST7796. Fixed in develop and just merged back to main.
If you update the submodule it should work.

I did not change the SPI_MODE3, this because there is also a  ESP32-2432S032R that uses the same bus...
Can do a check with another board to see this works also with the XPT2046.

I ordered one of those because is lacking in the collection of boards!

Thanks!

**Comment by rzeldent** [comment]
Not all has been changed, just a sec...

**Comment by rzeldent** [comment]
Also the other defines were changed. Tried the driver on the  ESP32-1732S019N. Works.

Also, on the ESP32-1732S019N tested the difference between SPI_MODE0 and SPI_MODE3. The timing for the data should be differences but I do not see any changing to SPI_MODE3. Is this really required?

**Comment by Keidran** [comment]
Mb I have bad cyd but MODE0 and MODE1 don't work, MODE2 and MODE3 works

**Comment by rzeldent** [comment]
Hi Keidran,

Thanks for the reply, I changed it in the driver to mode 3.
Maybe you can check if it works not as it should.

**Comment by Keidran** [comment]
What exactly needs to be checked, modes?

**Comment by rzeldent** [comment]
Well, updated the mode in the smartdisplay for the ST7789 to mode 3. Just a check to see if it works now on your device...

**Comment by Keidran** [comment]
As I wrote above, it works, like mode 2
And turned off the lcd_mirror_x. Although this is already possible because of the board itself.

**Comment by rzeldent** [comment]
Yes, that's also logical that the mirror_x is no longer required. Then also the touch mirror_x should be removed.
I'll also update this setting!

**Comment by Keidran** [comment]
For the touch, it was not set

**Comment by rzeldent** [comment]
Should also be fixed now in the definitions. Thanks for mentioning! 👍
