### ISSUE TITLE
Green LED & ST7789 ERROR_CHECK

### ISSUE THREAD

**Issue by Keidran** [rzeldent/esp32-smartdisplay#76]
https://github.com/rzeldent/esp32-smartdisplay/blob/cb0cf3378a0998ea713dc6687db013680fecaa81/src/esp32_smartdisplay.c#L152C31-L152C31
`digitalWrite(RGB_LED_B, !g); //Mb RGB_LED_G`

https://github.com/rzeldent/esp32-smartdisplay/blob/cb0cf3378a0998ea713dc6687db013680fecaa81/src/lvgl_st7789.c#L44C72-L44C87
`ESP_ERROR_CHECK(esp_lcd_new_panel_io_spi((esp_lcd_spi_bus_handle_t)ST7789_SPI_MOSI, &io_spi_config, &io_handle)); //Mb ST7789_SPI_HOST`

**Comment by rzeldent** [comment]
Hi Keidran,

Thank you very much for your issue; stupid typo's.
I've fixed them!

Thanks!
