### ISSUE TITLE
Esp32-8048S070 display, different version

### ISSUE THREAD

**Issue by Reneg973** [rzeldent/esp32-smartdisplay#90]
Hi,
there is a different version of this display, see https://www.makerfabs.com/sunton-esp32-s3-7-inch-tn-display-with-touch.html.

The colors were not right, but the image appeared to be ok, so I just changed the json color pins to this:
      "-DRGB_PANEL_R0=14",
      "-DRGB_PANEL_R1=21",
      "-DRGB_PANEL_R2=47",
      "-DRGB_PANEL_R3=48",
      "-DRGB_PANEL_R4=45",
      "-DRGB_PANEL_G0=9",
      "-DRGB_PANEL_G1=46",
      "-DRGB_PANEL_G2=3",
      "-DRGB_PANEL_G3=8",
      "-DRGB_PANEL_G4=16",
      "-DRGB_PANEL_G5=1",
      "-DRGB_PANEL_B0=15",
      "-DRGB_PANEL_B1=7",
      "-DRGB_PANEL_B2=6",
      "-DRGB_PANEL_B3=5",
      "-DRGB_PANEL_B4=4",
This is for version 1.1 of the display.
Touch seems to work, at least the button on your demo.

For the version 1.3 I received the screen had switched colors, luckily just red and blue are switched, so for V1.3 the defines are:
      "-DRGB_PANEL_R0=15",
      "-DRGB_PANEL_R1=7",
      "-DRGB_PANEL_R2=6",
      "-DRGB_PANEL_R3=5",
      "-DRGB_PANEL_R4=4",
      "-DRGB_PANEL_G0=9",
      "-DRGB_PANEL_G1=46",
      "-DRGB_PANEL_G2=3",
      "-DRGB_PANEL_G3=8",
      "-DRGB_PANEL_G4=16",
      "-DRGB_PANEL_G5=1",
      "-DRGB_PANEL_B0=14",
      "-DRGB_PANEL_B1=21",
      "-DRGB_PANEL_B2=47",
      "-DRGB_PANEL_B3=48",
      "-DRGB_PANEL_B4=45",

**Comment by Reneg973** [comment]
Note, on the wiki page they write about version 1.0 and 1.1. I own a version 1.3, but it seems compatible to version 1.1

**Comment by rzeldent** [comment]
Hi Rene,

Thanks for noticing this! Mystery solved!

I split (in the develop branch) the 8048S070C into two versions v11 and v13.

After this has been merged in the main branch, then so you'll need to update the board you're using in the platformio.ini file.

**Comment by rzeldent** [comment]
Think this was a typo. Now back to one version.
