### ISSUE TITLE
TFT is invert (touch rotated)

### ISSUE THREAD

**Issue by rzeldent** [rzeldent/esp32-smartdisplay#96]

**Comment by fcortijos** [comment]
I'm using the esp32-8048S070Cv13 board. The image is ok, but the touch coordinates are flipped 180 degrees. How to configure this?
tks

**Comment by fcortijos** [comment]
Nope, I'm using my own app. To make it "work" I had to change the json board with these two lines: 
      "-DTOUCH_SWAP_X=false",
      "-DTOUCH_SWAP_Y=false",

**Comment by rzeldent** [comment]
Think you're right, checked the history and a typo was present.
Will soon be fixed, now in develop

**Comment by fcortijos** [comment]
tks
